name: Auto Build Termux App
on: 
   workflow_dispatch:
     branches: [ master ]
   repository_dispatch:
    types: start auto build Termux
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Clone repository
      run: |
        git clone https://github.com/termux/termux-app termux_app
        git clone https://github.com/termux/termux-packages termux_packages
    - name: build packages
      run: |
        printf "开始编译packages\n"
        cd termux_packages/scripts
        #bash ./generate-bootstraps.sh
    - name: move
      run: |
        ls -l
        #mv termux_packages/scripts/*.zip termux_app/app/src/main/cpp/
    - name: Check version
      run: |
        remote_version=$(cat termux_app/app/build.gradle |grep "versionName \"" |awk -F "\"" '{print $2}')
        local_version=$(cat version.json |jq -r .app)
        echo "已编译版本--$local_version"
        echo "官方最新版本--$remote_version"
        if [ "$local_version" == "$remote_version" ];then
                printf "无最新版本!\n\n"
        fi
        echo "zt=$?" >> $GITHUB_ENV
        echo "remote_version=$remote_version" >> $GITHUB_ENV
        echo "local_version=$local_version" >> $GITHUB_ENV
    - name: Replace
      run: |
        ###
        cd termux_app
        rep(){ sed -i "s/$1/$2/g" $3 ;}
        str="app/src/main/res/values-zh-rCN/strings.xml"
        str2="terminal-view/src/main/res/values-zh-rCN/strings.xml"
        cp -r app/src/main/res/values app/src/main/res/values-zh-rCN
        cp -r terminal-view/src/main/res/values terminal-view/src/main/res/values-zh-rCN
        #rep "↹" "TAB" app/src/main/java/com/termux/app/terminal/io/extrakeys/ExtraKeysInfo.java
        #rep "ESC, TAB, CTRL, ALT, {key: '-', popup: '|'}, DOWN, UP" "ESC, {key: '-', popup: '|'}, {key: '\/', popup: '\\\\\\\\\\\\\\\\'}, HOME, UP, END, PGUP],[TAB, CTRL, ALT, LEFT, DOWN, RIGHT, PGDN" termux-shared/src/main/java/com/termux/shared/settings/properties/TermuxPropertyConstants.java
        rep "Copy" "复制" $str2
        rep "Paste" "粘贴" $str2
        rep "More" "更多" $str2
        rep "Abort" "中止" $str
        rep "Termux can only be installed on the primary user account." "Termux只能安装在主用户帐户." $str
        rep "Termux was unable to install the bootstrap packages." "Termux无法安装引导程序包." $str
        rep "Check your network connection and try again." "检查您的网络连接，然后再试一次." $str
        rep "Unable to install" "无法安装" $str
        rep "Try again" "再试一次" $str
        rep "Installing…" "安装中..." $str
        rep "Really kill this session?" "确定杀死这个会话吗？" $str
        rep "Edit" "编辑" $str
        rep "Open folder" "打开文件夹" $str
        rep "Save file in ~\/downloads\/" "保存文件到 ~\/downloads\/" $str
        rep "Help" "帮助" $str
        rep "Autofill password" "自动填充密码" $str
        rep "Kill process (%d)" "杀死会话 (%d)" $str
        rep "Close down existing ones before creating new." "在创建新的之前关闭现有的." $str
        rep "Max terminals reached" "终端到达最大数量了" $str
        rep "New session" "新建会话" $str
        rep "Failsafe" "新建系统会话" $str
        rep "Exit" "退出" $str
        rep "Acquire wakelock" "开启唤醒锁" $str
        rep "Release wakelock" "关闭唤醒锁" $str
        rep "Reset" "重置" $str
        rep "Terminal reset." "重置终端<" $str
        rep "Share transcript" "分享日志" $str
        rep "Select URL" "选择链接" $str
        rep "URL copied to clipboard" "URL复制到剪贴板" $str
        rep "Click URL to copy or long press to open" "点击链接复制或长按打开" $str
        rep "No URL found in the terminal." "在终端中找不到URL。" $str
        rep "Create" "创建" $str
        rep "New named session" "新命名的会话" $str
        rep "Set session name" "设置会话名" $str
        rep "Settings" "设置" $str
        rep "Set" "设置" $str
        rep "Send text to:" "发送文本至:" $str
        rep "Terminal transcript" "终端日志" $str
        rep "Termux user" "Termux用户" $str
        rep "Install" "安装" $str
        rep "The Termux:Style add-on is not installed." "Termux:Style插件没有安装." $str
        rep "Style" "风格" $str
        rep "Keep screen on" "保持屏幕常亮" $str
        rep "Report Issue" "报告问题" $str
        rep "Keyboard" "键盘" $str
        rep "Soft keyboard will be disabled." "禁用软键盘" $str
        rep "Soft keyboard will be enabled. (Default)" "启用软键盘.(默认)" $str
        rep "Debugging" "调试" $str
        rep "Logging" "日志" $str
        rep "Plugin Error Notifications" "插件错误通知" $str
        rep "Disable flashes and notifications for plugin errors." "禁用插件错误的闪烁和通知." $str
        rep "Show flashes and notifications for plugin errors. (Default)" "显示插件错误的闪烁和通知.(默认)" $str
        rep "Crash Report Notifications" "崩溃报告通知" $str
        rep "Disable notifications for crash reports." "禁用崩溃报告的通知" $str
        rep "Show notifications for crash reports. (Default)" "显示崩溃报告的通知.(默认)" $str
        #rep "The following file does not exist" "以下文件不存在" app/src/main/java/com/termux/filepicker/TermuxFileReceiverActivity.java
        #rep "Create this file as a script or a symlink - it will be called with the received file as only argument" "把使用的编辑器命令链接到此文件" app/src/main/java/com/termux/filepicker/TermuxFileReceiverActivity.java
        rep " session\" + (sessionCount == 1 ? \"\" : \"s\")" "个会话\" + (sessionCount == 1 ? \"\" : \"\")" app/src/main/java/com/termux/app/TermuxService.java
        rep "Process completed" "进程已结束" terminal-emulator/src/main/java/com/termux/terminal/TerminalSession.java
        rep "press Enter" "按回车关闭" terminal-emulator/src/main/java/com/termux/terminal/TerminalSession.java
        printf "修改完成----\n"
        rep "'x86', 'x86_64', 'armeabi-v7a', 'arm64-v8a'" "'arm64-v8a'" app/build.gradle
    - name: Build apk
      run: |
        printf "开始编译\n"
        cd termux_app
        ./gradlew assembleDebug
        tree app/build/outputs
    - name: Change local version
      run: |
          sed -i "s/.*app.*/\"app\":\"${remote_version}\",/g" version.json
          sed -i "s/.*app.*/\"app\":\"${remote_version}\",/g" README.md
          git config --global user.email "237586390@qq.com"
          git config --global user.name "voii"
    - name: Store generated APK file
      uses: actions/upload-artifact@v1
      with:
        name: termux-arm64
        path: ./termux_app/app/build/outputs/apk/debug/
