name: Auto Build Termux App
on: 
   workflow_dispatch:
     branches: [ master ]
   repository_dispatch:
    types: start auto build Termux
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Clone repository
      run: git clone https://github.com/termux/termux-packages termux_packages
    - name: Build
      run: |
        printf "开始编译\n"
        cd termux_packages/scripts
        bash ./generate-bootstraps.sh
        mv *.zip ../../
    - name: Store generated file
      if: env.zt == 0
      uses: actions/upload-artifact@v1
      with:
        name: termux-packages
        path: ./bootstrap-aarch64.zip
