name: Auto Build sketchware
on: 
   workflow_dispatch:
   repository_dispatch:
    types: start auto build Api
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: 拉取源代码
      run: git clone https://github.com/Sketchware-Pro/Sketchware-Pro sketch
    - name: Build
      run: |
        printf "开始编译\n"
        cd sketch
        gradle assembleDebug
        cp app/build/outputs/apk/debug/app-debug.apk ../sketchware.apk
        echo "编译结束"
    - name: Store generated APK file
      uses: actions/upload-artifact@v1
      with:
        name: termux-api
        path: ./sketch/app/build/outputs/apk/debug/app-debug.apk
