name: Auto Build sketchware
on: 
   workflow_dispatch:
   repository_dispatch:
    types: start auto build Api
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: 拉取源代码
      run: git clone https://github.com/termux/termux-api termux_api
    - name: Build
      run: |
        printf "开始编译\n"
        cd termux_api
        ./gradlew assembleDebug
        cp app/build/outputs/apk/debug/app-debug.apk ../Termux_api_${remote_version}.apk
        echo "编译结束"
    - name: Store generated APK file
      if: env.zt == 0
      uses: actions/upload-artifact@v1
      with:
        name: termux-api
        path: ./termux_api/app/build/outputs/apk/debug/app-debug.apk
